--apaga todos os dados existentes nas tabelas
BEGIN transaction;

DELETE FROM MENSAGEM;
DELETE FROM CONVERSA_PARTICIPANTES;
DELETE FROM CONVERSA;
DELETE FROM AMIGOS;
DELETE FROM JOGADOR_CRACHA;
DELETE FROM CRACHA;
DELETE FROM JOGADOR_PARTIDA_MULTI_JOGADOR;
DELETE FROM PARTIDA_MULTI_JOGADOR;
DELETE FROM PARTIDA_NORMAL;
DELETE FROM PARTIDA;
DELETE FROM COMPRAS;
DELETE FROM JOGO;
DELETE FROM JOGADOR;
DELETE FROM REGIAO;

END transaction;
